# Generated by Django 3.2.3 on 2021-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20210529_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
