# Generated by Django 3.2.3 on 2021-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_seller_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(),
        ),
    ]
