# Generated by Django 3.2.3 on 2021-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(),
        ),
    ]
