# Generated by Django 3.2.3 on 2021-05-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
